---
# tasks file for deploy_haproxy
- name: Install haproxy
  apt:
    name: haproxy
    state: latest
- name: Configure haproxy
  copy:
    src: haproxy.cfg
    dest: "{{ dest_folder }}"
    mode: 0555
  notify: Restart haproxy
- name: Start haproxy
  service:
    name: haproxy
    state: started
    enabled: yes